language: php
php:
  - 7.1.9
  - 7.2

branches:
  only:
    - develop/v1.0.0
    - master

services:
  - mysql

env:
  - APP_DEBUG=false

install:
  - composer install --prefer-dist --optimize-autoloader --no-dev

script:
  - phpunit -c phpunit.xml